name: Go

on:
  push:
    branches: [ 'main', 'release-*' ]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  FORCE_COLOR: true

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.22'
          - '1.23'
    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Test
        run: go run gotest.tools/gotestsum@v1.12.0 --format testname --
          -race -count=1 -short ./...
